/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface LenderInterface extends ethers.utils.Interface {
  functions: {
    "_actualColl()": FunctionFragment;
    "_actualDebt()": FunctionFragment;
    "_collateral()": FunctionFragment;
    "_fee()": FunctionFragment;
    "_minDebt()": FunctionFragment;
    "_minPositionCollateralizationRatio()": FunctionFragment;
    "_minSystemCollateralizationRatio()": FunctionFragment;
    "_nusd()": FunctionFragment;
    "_openedColl()": FunctionFragment;
    "_openedDebt()": FunctionFragment;
    "_oracle()": FunctionFragment;
    "_positions(address)": FunctionFragment;
    "liquidate(address,bytes)": FunctionFragment;
    "owner()": FunctionFragment;
    "positionOf(address)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "setFee(uint256)": FunctionFragment;
    "setMinDebt(uint256)": FunctionFragment;
    "setMinPositionCollateralizationRatio(uint256)": FunctionFragment;
    "setMinSystemCollateralizationRatio(uint256)": FunctionFragment;
    "totalCollateralizationRatio(uint256)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "update(int256,int256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "_actualColl",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "_actualDebt",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "_collateral",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "_fee", values?: undefined): string;
  encodeFunctionData(functionFragment: "_minDebt", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "_minPositionCollateralizationRatio",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "_minSystemCollateralizationRatio",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "_nusd", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "_openedColl",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "_openedDebt",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "_oracle", values?: undefined): string;
  encodeFunctionData(functionFragment: "_positions", values: [string]): string;
  encodeFunctionData(
    functionFragment: "liquidate",
    values: [string, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "positionOf", values: [string]): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMinDebt",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMinPositionCollateralizationRatio",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMinSystemCollateralizationRatio",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalCollateralizationRatio",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "update",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "_actualColl",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_actualDebt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_collateral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "_fee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "_minDebt", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "_minPositionCollateralizationRatio",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_minSystemCollateralizationRatio",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "_nusd", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "_openedColl",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_openedDebt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "_oracle", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "_positions", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "liquidate", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "positionOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setFee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setMinDebt", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setMinPositionCollateralizationRatio",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMinSystemCollateralizationRatio",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalCollateralizationRatio",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "update", data: BytesLike): Result;

  events: {
    "Liquidate(address,address)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "Update(address,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Liquidate"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Update"): EventFragment;
}

export class Lender extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: LenderInterface;

  functions: {
    _actualColl(overrides?: CallOverrides): Promise<[BigNumber]>;

    _actualDebt(overrides?: CallOverrides): Promise<[BigNumber]>;

    _collateral(overrides?: CallOverrides): Promise<[string]>;

    _fee(overrides?: CallOverrides): Promise<[BigNumber]>;

    _minDebt(overrides?: CallOverrides): Promise<[BigNumber]>;

    _minPositionCollateralizationRatio(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    _minSystemCollateralizationRatio(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    _nusd(overrides?: CallOverrides): Promise<[string]>;

    _openedColl(overrides?: CallOverrides): Promise<[BigNumber]>;

    _openedDebt(overrides?: CallOverrides): Promise<[BigNumber]>;

    _oracle(overrides?: CallOverrides): Promise<[string]>;

    _positions(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber] & { debt: BigNumber; coll: BigNumber }>;

    liquidate(
      owner: string,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    positionOf(
      owner: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber] & { coll: BigNumber; debt: BigNumber }>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setFee(
      fee: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setMinDebt(
      minDebt: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setMinPositionCollateralizationRatio(
      minPositionCollateralizationRatio: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setMinSystemCollateralizationRatio(
      minSystemCollateralizationRatio: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    totalCollateralizationRatio(
      price: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    update(
      collDelta: BigNumberish,
      debtDelta: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  _actualColl(overrides?: CallOverrides): Promise<BigNumber>;

  _actualDebt(overrides?: CallOverrides): Promise<BigNumber>;

  _collateral(overrides?: CallOverrides): Promise<string>;

  _fee(overrides?: CallOverrides): Promise<BigNumber>;

  _minDebt(overrides?: CallOverrides): Promise<BigNumber>;

  _minPositionCollateralizationRatio(
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  _minSystemCollateralizationRatio(
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  _nusd(overrides?: CallOverrides): Promise<string>;

  _openedColl(overrides?: CallOverrides): Promise<BigNumber>;

  _openedDebt(overrides?: CallOverrides): Promise<BigNumber>;

  _oracle(overrides?: CallOverrides): Promise<string>;

  _positions(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber] & { debt: BigNumber; coll: BigNumber }>;

  liquidate(
    owner: string,
    data: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  owner(overrides?: CallOverrides): Promise<string>;

  positionOf(
    owner: string,
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber] & { coll: BigNumber; debt: BigNumber }>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setFee(
    fee: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setMinDebt(
    minDebt: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setMinPositionCollateralizationRatio(
    minPositionCollateralizationRatio: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setMinSystemCollateralizationRatio(
    minSystemCollateralizationRatio: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  totalCollateralizationRatio(
    price: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  update(
    collDelta: BigNumberish,
    debtDelta: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    _actualColl(overrides?: CallOverrides): Promise<BigNumber>;

    _actualDebt(overrides?: CallOverrides): Promise<BigNumber>;

    _collateral(overrides?: CallOverrides): Promise<string>;

    _fee(overrides?: CallOverrides): Promise<BigNumber>;

    _minDebt(overrides?: CallOverrides): Promise<BigNumber>;

    _minPositionCollateralizationRatio(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    _minSystemCollateralizationRatio(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    _nusd(overrides?: CallOverrides): Promise<string>;

    _openedColl(overrides?: CallOverrides): Promise<BigNumber>;

    _openedDebt(overrides?: CallOverrides): Promise<BigNumber>;

    _oracle(overrides?: CallOverrides): Promise<string>;

    _positions(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber] & { debt: BigNumber; coll: BigNumber }>;

    liquidate(
      owner: string,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    owner(overrides?: CallOverrides): Promise<string>;

    positionOf(
      owner: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber] & { coll: BigNumber; debt: BigNumber }>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    setFee(fee: BigNumberish, overrides?: CallOverrides): Promise<void>;

    setMinDebt(minDebt: BigNumberish, overrides?: CallOverrides): Promise<void>;

    setMinPositionCollateralizationRatio(
      minPositionCollateralizationRatio: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setMinSystemCollateralizationRatio(
      minSystemCollateralizationRatio: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    totalCollateralizationRatio(
      price: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    update(
      collDelta: BigNumberish,
      debtDelta: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    Liquidate(
      owner?: string | null,
      liquidator?: null
    ): TypedEventFilter<
      [string, string],
      { owner: string; liquidator: string }
    >;

    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;

    Update(
      owner?: string | null,
      coll?: null,
      debt?: null
    ): TypedEventFilter<
      [string, BigNumber, BigNumber],
      { owner: string; coll: BigNumber; debt: BigNumber }
    >;
  };

  estimateGas: {
    _actualColl(overrides?: CallOverrides): Promise<BigNumber>;

    _actualDebt(overrides?: CallOverrides): Promise<BigNumber>;

    _collateral(overrides?: CallOverrides): Promise<BigNumber>;

    _fee(overrides?: CallOverrides): Promise<BigNumber>;

    _minDebt(overrides?: CallOverrides): Promise<BigNumber>;

    _minPositionCollateralizationRatio(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    _minSystemCollateralizationRatio(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    _nusd(overrides?: CallOverrides): Promise<BigNumber>;

    _openedColl(overrides?: CallOverrides): Promise<BigNumber>;

    _openedDebt(overrides?: CallOverrides): Promise<BigNumber>;

    _oracle(overrides?: CallOverrides): Promise<BigNumber>;

    _positions(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    liquidate(
      owner: string,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    positionOf(owner: string, overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setFee(
      fee: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setMinDebt(
      minDebt: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setMinPositionCollateralizationRatio(
      minPositionCollateralizationRatio: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setMinSystemCollateralizationRatio(
      minSystemCollateralizationRatio: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    totalCollateralizationRatio(
      price: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    update(
      collDelta: BigNumberish,
      debtDelta: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    _actualColl(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    _actualDebt(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    _collateral(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    _fee(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    _minDebt(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    _minPositionCollateralizationRatio(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    _minSystemCollateralizationRatio(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    _nusd(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    _openedColl(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    _openedDebt(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    _oracle(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    _positions(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    liquidate(
      owner: string,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    positionOf(
      owner: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setFee(
      fee: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setMinDebt(
      minDebt: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setMinPositionCollateralizationRatio(
      minPositionCollateralizationRatio: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setMinSystemCollateralizationRatio(
      minSystemCollateralizationRatio: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    totalCollateralizationRatio(
      price: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    update(
      collDelta: BigNumberish,
      debtDelta: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
