/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { OracleFake, OracleFakeInterface } from "../OracleFake";

const _abi = [
  {
    inputs: [],
    name: "_price",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "observe",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "price",
        type: "uint256",
      },
    ],
    name: "set",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b5060c28061001f6000396000f3fe6080604052348015600f57600080fd5b5060043610603c5760003560e01c806314fc78fc146041578063235b6ea114605957806360fe47b114605f575b600080fd5b6047607b565b60408051918252519081900360200190f35b60476081565b607960048036036020811015607357600080fd5b50356087565b005b60005490565b60005481565b60005556fea264697066735822122075757a41fb8c83e10265c7a6a976fdb007a109f32b053b10b439a874bdcded6164736f6c63430007060033";

export class OracleFake__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<OracleFake> {
    return super.deploy(overrides || {}) as Promise<OracleFake>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): OracleFake {
    return super.attach(address) as OracleFake;
  }
  connect(signer: Signer): OracleFake__factory {
    return super.connect(signer) as OracleFake__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): OracleFakeInterface {
    return new utils.Interface(_abi) as OracleFakeInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): OracleFake {
    return new Contract(address, _abi, signerOrProvider) as OracleFake;
  }
}
